# Generated by Django 2.0 on 2018-06-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=20)),
                ('groupname', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User_Login_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
