# Generated by Django 2.0 on 2018-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(max_length=256)),
                ('incident_number', models.CharField(max_length=256)),
                ('priority', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('incident_opened', models.CharField(max_length=256)),
                ('incident_duration', models.CharField(max_length=256)),
                ('what_happened', models.CharField(max_length=256)),
                ('business_impact', models.CharField(max_length=256)),
                ('service_impact', models.CharField(max_length=256)),
                ('key_groups_and_people_involved', models.CharField(max_length=256)),
                ('what_we_discovered', models.CharField(max_length=256)),
                ('what_finally_fixed_the_issue', models.CharField(max_length=256)),
                ('post_recovery_action_items', models.CharField(max_length=256)),
                ('design_issues', models.CharField(max_length=256)),
                ('chronology_of_the_incident', models.CharField(max_length=256)),
                ('flagged_for_reliability', models.CharField(max_length=256)),
                ('date_and_time_flagged_for_reliability', models.CharField(max_length=256)),
                ('reliability_record_number', models.CharField(max_length=256)),
                ('time_down', models.CharField(max_length=256)),
                ('date_and_time_issue_resolved', models.CharField(max_length=256)),
                ('did_we_receive_an_alert', models.CharField(max_length=256)),
                ('date_and_time_alert_received', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Message_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user_login_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_login_details',
            name='email',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
