# Generated by Django 2.0.6 on 2018-07-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email_History',
        ),
    ]
