# Generated by Django 2.0.6 on 2018-07-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0002_delete_email_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=256)),
                ('communication_type', models.CharField(max_length=256)),
                ('incident_number', models.CharField(max_length=256)),
                ('priority', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('incident_opened_date', models.CharField(max_length=256)),
                ('incident_opened_time', models.CharField(max_length=256)),
                ('incident_duration_days', models.CharField(max_length=256)),
                ('incident_duration_hr', models.CharField(max_length=256)),
                ('incident_duration_min', models.CharField(max_length=256)),
                ('what_happened', models.CharField(max_length=256)),
                ('business_impact', models.CharField(max_length=256)),
                ('service_impact', models.CharField(max_length=256)),
                ('key_groups_and_people_involved', models.CharField(max_length=256)),
                ('what_we_discovered', models.CharField(max_length=256)),
                ('what_finally_fixed_the_issue', models.CharField(max_length=256)),
                ('post_recovery_action_items', models.CharField(max_length=256)),
                ('design_issues', models.CharField(max_length=256)),
                ('chronology_of_the_incident', models.CharField(max_length=256)),
                ('flagged_for_reliability', models.CharField(max_length=256)),
                ('date_and_time_flagged_for_reliability_date', models.CharField(max_length=256)),
                ('date_and_time_flagged_for_reliability_time', models.CharField(max_length=256)),
                ('reliability_record_number', models.CharField(max_length=256)),
                ('time_down_date', models.CharField(max_length=256)),
                ('time_down_time', models.CharField(max_length=256)),
                ('date_and_time_issue_resolved_date', models.CharField(max_length=256)),
                ('date_and_time_issue_resolved_time', models.CharField(max_length=256)),
                ('did_we_receive_an_alert', models.CharField(max_length=256)),
                ('date_and_time_alert_received_date', models.CharField(max_length=256)),
                ('date_and_time_alert_received_time', models.CharField(max_length=256)),
            ],
        ),
    ]
