# Generated by Django 2.0 on 2018-06-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0003_email_history_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_history',
            old_name='group',
            new_name='groupname',
        ),
        migrations.AddField(
            model_name='message_history',
            name='groupname',
            field=models.CharField(default='A', max_length=256),
            preserve_default=False,
        ),
    ]
