# Generated by Django 2.0 on 2018-06-22 05:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0006_auto_20180622_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 5, 10, 2, 920774, tzinfo=utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
