# Generated by Django 2.0 on 2018-06-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0007_auto_20180622_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='username',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
