# Generated by Django 2.0 on 2018-06-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0009_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='username',
            field=models.CharField(max_length=256),
        ),
    ]
