# Generated by Django 2.0 on 2018-06-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0010_auto_20180622_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=256)),
                ('message', models.CharField(max_length=256)),
            ],
        ),
    ]
